<?php defined('BASEPATH') OR exit('No direct script access allowed');

require_once APPPATH . '/third_party/PHPExcel.php';

/**
 * The encapsulation of the PHPExcel Library.
 */
class Lib_excel extends PHPExcel { 
	/**
	 * The constructor of the class.
	 */
    public function __construct() { 
        parent::__construct();
    }

    /**
     * Get data from an excel file.
     * @param  String $file_path - the path of the excel file
     * @return an array contains data which is read from the
     *         excel file.
     */
    public function get_data_from_excel($file_path) {
        $file_ext   = substr( $file_path, -3 );
        if ( strtolower($file_ext) == 'xls' ) {
            $reader = PHPExcel_IOFactory::createReader('Excel5');
        } else {
            $reader = PHPExcel_IOFactory::createReader('Excel2007');
        }
        
        $obj                = $reader->load($file_path);
        $sheet              = $obj->getSheet(0); 
        $number_of_rows     = $sheet->getHighestRow();
        $number_of_columns  = PHPExcel_Cell::columnIndexFromString($sheet->getHighestColumn());
        $data = array();
        for ( $row = 1; $row <= $number_of_rows; ++ $row ) {
        	for ( $column = 0; $column < $number_of_columns; ++ $column ) {
        		$columnName = PHPExcel_Cell::stringFromColumnIndex($column);
        		$data[$row - 1][$column] = $sheet->getCellByColumnAndRow($column, $row)->getValue();
        	}
        }
        return $data;
    }

    /**
     * Export data to an exce file.
     * @param Array  $data      - the data within an array that needed to export
     * @param String $file_path - the path where the excel file to store
     */
    public function export_data_to_excel($data, $file_path) {
        $phpExcel = new PHPExcel();

        $phpExcel->getProperties()->setCreator("House Statistics for Zhejiang Provice")
                 ->setLastModifiedBy("National Bureau of Statisticsof Zhejiang Province")
                 ->setTitle("House Statistics")
                 ->setSubject("House Statistics")
                 ->setDescription("House Statistics, generated by PHPExcel.")
                 ->setKeywords("house statistics Zhejiang")
                 ->setCategory("house statistics");
        $phpExcel->getActiveSheet()->setTitle('House Statistics');
        $phpExcel->setActiveSheetIndex(0);

        $row_index      = 1;
        foreach ( $data as $row ) {
            $column_index   = 'A';
            foreach ( $row as $column ) {
                $phpExcel->getActiveSheet()->SetCellValue($column_index.$row_index, $column);
                ++ $column_index;
            }
            ++ $row_index;
        }

        $writer  = PHPExcel_IOFactory::createWriter($phpExcel, 'Excel2007');
        $writer->save($file_path);
    }
	
	/**
	 * Convert the datetime format from Excel to PHP.
	 * @param  String $days - datetime format in Excel
	 * @return a datetime format in PHP
	 */
	public function excel2timestamp($days) {
		// But you must subtract 1 to get the correct timestamp 
		$ts = mktime(0, 0, 0, 1, $days - 1, 1900); 
		// So, this would then match Excel's representation: 
		return date("Y-m-d", $ts);
	}
}